version: '3'
services:
  nginx:
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
        - "80:80"
    volumes:
        - ./app:/app:cached
        - ./docker/conf/nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    links:
        - php
  php:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    volumes:
        - ./app:/app:cached
        - ./docker/conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
    links:
        - mysql 

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
        - ./conf:/conf/
    environment:
        MYSQL_DATABASE: 'prep50mock'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: 'root'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - mysql
    ports:
        - 8080:80
    environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=mysql

  redis:
    image: 'bitnami/redis:latest'
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes